import ast
import json
import re
from collections import defaultdict
from math import hypot

from PIL import Image, ImageDraw

from multi_agent_collaborative_scene_generation_system.utils.fonts import (
    get_font,
    additional_colors,
)
from multi_agent_collaborative_scene_generation_system.utils.json_tools import (
    parse_json,
    decode_json_points,
)


def load_boxes(json_text: str):
    body = parse_json(json_text)

    try:
        data = json.loads(body)
    except Exception:
        end_idx = body.rfind('"}') + len('"}')
        data = json.loads(body[:end_idx] + "]")

    if not isinstance(data, list):
        data = [data]

    cleaned = []

    for item in data:
        if (
            "bbox_2d" in item
            and "label" in item
            and isinstance(item["bbox_2d"], (list, tuple))
            and len(item["bbox_2d"]) == 4
        ):
            try:
                x1, y1, x2, y2 = [int(v) for v in item["bbox_2d"]]
            except Exception:
                continue

            if (
                0 <= x1 <= 999
                and 0 <= y1 <= 999
                and 0 <= x2 <= 999
                and 0 <= y2 <= 999
            ):
                cleaned.append(
                    {
                        "bbox_2d": [x1, y1, x2, y2],
                        "label": str(item["label"]),
                    }
                )

    return cleaned


def normalize_shape_name(name: str) -> str:
    alias = {
        "rectangle": "rect",
        "square": "rect",
        "parallelogram": "para",
        "rhombus": "rhom",
        "trapezoid": "trap",
        "pentagon": "penta",
        "hexagon": "hexa",
        "heptagon": "hepta",
        "octagon": "octa",
        "polygon": "poly",
        "line_segment": "line",
    }

    return alias.get(name, name)


def build_points_prompt_with_boxes(boxes):
    prompt_points = (
        "You are a visual keypoint annotation assistant. In a mathematical or "
        "geometric scene image generated by Manim, output keypoints for each "
        "identified geometric object and return a JSON array. Output only the "
        "array itself. Do not output any extra text or Markdown. "
        "Instance numbering rule: order instances from top to bottom and from "
        "left to right within the same row. For objects of the same class, number "
        "them as #1, #2, #3, and so on. The numbering must match the detection box "
        "order. "
        "Coordinate system: use normalized coordinates from 0 to 999. Each point "
        'must use the format {"point_2d":[x,y],"label":"..."}. x and y must be '
        "integers. "
        "Keypoint naming by category: "
        "triangle: three vertices clockwise -> triangle_v1..v3; "
        "square/rectangle: four vertices clockwise -> rect_v1..v4; "
        "parallelogram: four vertices clockwise -> para_v1..v4; "
        "rhombus: four vertices clockwise -> rhom_v1..v4; "
        "trapezoid: four vertices clockwise -> trap_v1..v4; "
        "kite: four vertices clockwise -> kite_v1..v4; "
        "pentagon: five vertices clockwise -> penta_v1..v5; "
        "hexagon: six vertices clockwise -> hexa_v1..v6; "
        "heptagon: seven vertices clockwise -> hepta_v1..v7; "
        "octagon: eight vertices clockwise -> octa_v1..v8; "
        "polygon with more than eight vertices: all vertices clockwise -> poly_v1..vN; "
        "circle: center and one point on the circle -> circle_center, circle_rpoint; "
        "ellipse: center and one endpoint of the major axis -> ellipse_center, ellipse_axis; "
        "line_segment: two endpoints -> line_p1, line_p2; "
        "arrow: tail and arrow head -> arrow_tail, arrow_head; "
        "axis: origin and one positive tick point -> axis_origin, axis_pos; "
        "text: approximate text center -> text_center. "
        "For multiple instances of the same category, append the instance number "
        "to each label, such as rect_v1#1..rect_v4#1. The second rectangle must "
        "be rect_v1#2..rect_v4#2. Apply the same rule to all other categories. "
        "Consistency rule: if an object has been clearly identified as a specific "
        "category such as square, use the corresponding prefix. For square and "
        "rectangle, use the unified rect_ prefix. Do not output conflicting "
        "category keypoints. Ignore watermarks, decorative elements, and camera frames."
    )

    per_class_counter = defaultdict(int)
    annotated = []

    for box in boxes:
        raw_label = str(box["label"])
        class_norm = normalize_shape_name(raw_label)
        per_class_counter[class_norm] += 1
        instance_id = per_class_counter[class_norm]
        annotated.append((class_norm, instance_id, raw_label, box["bbox_2d"]))

    lines = []
    lines.append(
        "Detected object list: output keypoints according to the following order "
        "and numbering. Annotate keypoints only within the corresponding bbox:"
    )

    for class_norm, instance_id, raw_label, (x1, y1, x2, y2) in annotated:
        lines.append(
            f"- {raw_label} -> instance #{instance_id}, "
            f"bbox_2d=[{x1},{y1},{x2},{y2}]"
        )

    constraints = (
        "Strict constraints:\n"
        "1) Instance numbers must exactly match the detected object list above. "
        "Numbering is independent within each class.\n"
        "2) Every keypoint label must include the #instance suffix, such as "
        "rect_v1#2 or triangle_v3#1.\n"
        "3) Find keypoints only within the corresponding bbox. If uncertain, "
        "leave that instance empty. Do not invent keypoints.\n"
        "4) Coordinates must be normalized integers from 0 to 999. Output only "
        "a pure JSON array with no explanatory text.\n"
    )

    return prompt_points + "\n" + "\n".join(lines) + "\n" + constraints


def plot_bounding_boxes(im: Image.Image, bounding_boxes: str):
    img = im
    width, height = img.size
    print("Image size:", img.size)

    draw = ImageDraw.Draw(img)
    font = get_font(14)

    colors = [
        "red",
        "green",
        "blue",
        "yellow",
        "orange",
        "pink",
        "purple",
        "brown",
        "gray",
        "beige",
        "turquoise",
        "cyan",
        "magenta",
        "lime",
        "navy",
        "maroon",
        "teal",
        "olive",
        "coral",
        "lavender",
        "violet",
        "gold",
        "silver",
    ] + additional_colors

    bbox_str = parse_json(bounding_boxes)

    try:
        detections = ast.literal_eval(bbox_str)
    except Exception:
        end_idx = bbox_str.rfind('"}') + len('"}')
        detections = ast.literal_eval(bbox_str[:end_idx] + "]")

    if not isinstance(detections, list):
        detections = [detections]

    for i, item in enumerate(detections):
        if "bbox_2d" not in item:
            continue

        x1n, y1n, x2n, y2n = item["bbox_2d"]
        color = colors[i % len(colors)]

        x1 = int(x1n / 1000 * width)
        y1 = int(y1n / 1000 * height)
        x2 = int(x2n / 1000 * width)
        y2 = int(y2n / 1000 * height)

        if x1 > x2:
            x1, x2 = x2, x1

        if y1 > y2:
            y1, y2 = y2, y1

        draw.rectangle(
            ((x1, y1), (x2, y2)),
            outline=color,
            width=3,
        )

        label = item.get("label", "")

        if label:
            draw.text(
                (x1 + 8, y1 + 6),
                label,
                fill=color,
                font=font,
            )


def parse_label(label: str):
    instance_id = 1

    if "#" in label:
        try:
            instance_id = int(label.split("#")[-1])
        except Exception:
            instance_id = 1

    base = label.split("#")[0]

    if "_" in base:
        shape, vertex = base.split("_", 1)
    else:
        shape, vertex = base, ""

    alias = {
        "rectangle": "rect",
        "square": "rect",
        "parallelogram": "para",
        "rhombus": "rhom",
        "trapezoid": "trap",
        "pentagon": "penta",
        "hexagon": "hexa",
        "heptagon": "hepta",
        "octagon": "octa",
        "polygon": "poly",
        "line_segment": "line",
    }

    shape_norm = alias.get(shape, shape)

    return shape_norm, instance_id, vertex


def connect_groups_and_shapes(draw, groups, color_map):
    closed_shapes = {
        "triangle",
        "rect",
        "para",
        "rhom",
        "trap",
        "kite",
        "penta",
        "hexa",
        "hepta",
        "octa",
        "poly",
    }
    line_like = {
        "line",
        "arrow",
        "axis",
    }

    for key, points in groups.items():
        shape_norm, instance_id = key
        color = color_map.get(key, "white")

        def vertex_index(point):
            match = re.search(r"^v(\d+)$", point["vertex"])
            return int(match.group(1)) if match else 10**9

        ordered = sorted(points, key=vertex_index)

        if shape_norm == "circle":
            candidates = {point["vertex"]: point for point in ordered}

            if "center" in candidates and "rpoint" in candidates:
                cx, cy = candidates["center"]["pt"]
                rx, ry = candidates["rpoint"]["pt"]
                radius = hypot(rx - cx, ry - cy)

                draw.ellipse(
                    [
                        (cx - radius, cy - radius),
                        (cx + radius, cy + radius),
                    ],
                    outline=color,
                    width=2,
                )

            continue

        if shape_norm in line_like:
            name_order = {
                "line": ["p1", "p2"],
                "arrow": ["tail", "head"],
                "axis": ["origin", "pos"],
            }
            order = name_order.get(shape_norm, [])
            line_points = []

            for name in order:
                for point in points:
                    if point["vertex"] == name:
                        line_points.append(point["pt"])
                        break

            if len(line_points) >= 2:
                draw.line(
                    [line_points[0], line_points[1]],
                    fill=color,
                    width=2,
                )

            continue

        if shape_norm in closed_shapes:
            polygon = [
                point["pt"]
                for point in ordered
                if re.match(r"^v\d+$", point["vertex"])
            ]

            if len(polygon) >= 3:
                draw.line(
                    polygon + [polygon[0]],
                    fill=color,
                    width=2,
                )

            continue


def plot_points(im: Image.Image, text: str):
    img = im
    width, height = img.size

    draw = ImageDraw.Draw(img)
    font = get_font(14)

    colors = [
        "red",
        "green",
        "blue",
        "yellow",
        "orange",
        "pink",
        "purple",
        "brown",
        "gray",
        "beige",
        "turquoise",
        "cyan",
        "magenta",
        "lime",
        "navy",
        "maroon",
        "teal",
        "olive",
        "coral",
        "lavender",
        "violet",
        "gold",
        "silver",
    ] + additional_colors

    points, labels = decode_json_points(text)

    print("Parsed points:", points)
    print("Parsed descriptions:", labels)

    debug_show = False

    if not points:
        if debug_show:
            img.show()
        return

    groups = {}
    color_map = {}

    for i, (nx, ny) in enumerate(points):
        label = labels[i] if i < len(labels) else ""
        color = colors[i % len(colors)]

        px = int(nx) / 1000 * width
        py = int(ny) / 1000 * height

        radius = 2

        draw.ellipse(
            [
                (px - radius, py - radius),
                (px + radius, py + radius),
            ],
            fill=color,
        )

        if label:
            draw.text(
                (px - 20, py + 6),
                label,
                fill=color,
                font=font,
            )

        if label:
            shape_norm, instance_id, vertex = parse_label(label)
            key = (shape_norm, instance_id)

            groups.setdefault(key, []).append(
                {
                    "label": label,
                    "pt": (px, py),
                    "vertex": vertex,
                }
            )
            color_map.setdefault(key, color)

    connect_groups_and_shapes(draw, groups, color_map)