from typing import Any


class SSRM:
    def put(self, layer: str, key: str, value: Any) -> "SSRM": ...
    def get(self, layer: str, key: str, default: Any = None) -> Any: ...
    def get_val(self, key: str, default: Any = None) -> Any: ...
    def add(self, layer: str, key: str, value: Any) -> "SSRM": ...
    def clear(self) -> "SSRM": ...
    def save(self, path: str | None = None) -> Any: ...


def load_model(*args: Any, **kwargs: Any) -> SSRM: ...


ssrm: SSRM