import os
import time
import uuid

from config import cfg

from multi_agent_collaborative_scene_generation_system.multi_agent import (
    ClientFactory,
    AgentFactory,
)
from multi_agent_collaborative_scene_generation_system.utils import (
    error_tool,
    save_generation_metrics_json,
    generate_video,
    extract_uniform_frames_as_base64,
    copy_frames_to_target_folder,
    read_temp_file,
    save_images_with_sections,
    write_last_code,
    write_scene_code_to_file,
    read_error_log,
    copy_ssrm_to_target_folder,
    copy_user_data_to_generation_data,
    extract_scene_classes,
)
from multi_agent_collaborative_scene_generation_system.module.hdrm import RAGDataClient
from multi_agent_collaborative_scene_generation_system.model.ssrm import ssrm


client = ClientFactory.create_client("azure", deployment="gpt-5-chat")

orchestration_agent = AgentFactory.create_agent("orchestration", client)
rendering_agent = AgentFactory.create_agent("rendering", client)
narration_agent = AgentFactory.create_agent("narration", client)

rag_data_client = RAGDataClient.create()
user_data_folder = cfg.USER_DATA_FOLDER

curr_version = 0


async def generation_video(
    topic: str,
    description: str,
    difficulty: str,
    max_retries: int = 5,
):
    global curr_version
    curr_version = 0

    start_perf = time.perf_counter()
    started_at_ms = int(time.time() * 1000)

    ssrm.clear()

    ssrm.put("Semantic layer", "topic", topic)
    ssrm.put("Semantic layer", "description", description)

    user_message = f"""topic: {topic} \n description: {description}"""
    read_temp_file(user_message)

    quality = "low"

    print("Orchestration agent is generating the scene plan.")
    scene_plan = await orchestration_agent.scene_plan()
    ssrm.put("Semantic layer", "scene_plan", scene_plan)
    print(f"Scene plan generated by orchestration agent: {scene_plan}")

    print("Orchestration agent is generating the visual storyboard.")
    scene_vision_storyboard = await orchestration_agent.scene_vision_storyboard()
    ssrm.put("Semantic layer", "scene_vision_storyboard", scene_vision_storyboard)
    print(f"Visual storyboard generated by orchestration agent: {scene_vision_storyboard}")

    print("Orchestration agent is generating the scene implementation.")
    scene_implementation = await orchestration_agent.scene_implementation()
    ssrm.put("Semantic layer", "scene_implementation", scene_implementation)
    print(f"Scene implementation generated by orchestration agent: {scene_implementation}")

    print("Orchestration agent is generating the technical implementation.")
    scene_technical_implementation = await orchestration_agent.scene_technical_implementation()
    ssrm.put(
        "Semantic layer",
        "scene_technical_implementation",
        scene_technical_implementation,
    )
    print(
        "Technical implementation generated by orchestration agent: "
        f"{scene_technical_implementation}"
    )

    print("Orchestration agent is generating the scene animation plan.")
    scene_animation = await orchestration_agent.scene_animation()
    ssrm.put("Semantic layer", "scene_animation", scene_animation)
    print(f"Scene animation plan generated by orchestration agent: {scene_animation}")

    print("Orchestration agent is generating the technical implementation extractor.")
    technical_implementation_extractor = (
        await orchestration_agent.scene_technical_implementation_extractor()
    )
    ssrm.put(
        "Semantic layer",
        "scene_technical_implementation_extractor",
        technical_implementation_extractor,
    )
    print(
        "Technical implementation extractor generated by orchestration agent: "
        f"{technical_implementation_extractor}"
    )

    print("Retrieving information from the hierarchical directory retrieval module.")
    rag_information = rag_data_client.search_by_rag_database(
        technical_implementation_extractor
    )
    ssrm.put("Semantic layer", "rag_information", rag_information)
    print(f"Retrieved RAG information: {rag_information}")

    print("Orchestration agent is retrieving geometric parameter control information.")
    geometric_parameter_control_module_information = (
        orchestration_agent.get_geometric_parameter_control_module_information()
    )
    ssrm.put(
        "Semantic layer",
        "geometric_parameter_control_module_information",
        geometric_parameter_control_module_information,
    )
    print(
        "Geometric parameter control information generated by orchestration agent: "
        f"{geometric_parameter_control_module_information}"
    )

    print("Narration agent is generating the scene narration.")
    scene_narration = await narration_agent.scene_narration()
    ssrm.put("Semantic layer", "scene_narration", scene_narration)
    print(f"Scene narration generated by narration agent: {scene_narration}")

    uuid_str = str(uuid.uuid4())

    print("Rendering agent is generating the scene code and initial geometric structure.")
    scene_code, geometric_structure_extraction = await rendering_agent.code_generation()

    ssrm.put("Semantic layer", "scene_code", scene_code)
    ssrm.put(
        "Geometric structure layer",
        "geometric_structure_extraction",
        geometric_structure_extraction,
    )

    print(f"Scene code generated by rendering agent: {scene_code}")
    print(
        "Initial geometric structure generated by rendering agent: "
        f"{geometric_structure_extraction}"
    )

    target_folder = f"{user_data_folder}/user_data_{uuid_str}"

    last_code = scene_code
    ssrm.put("Semantic layer", "scene_code", last_code)

    class_name = extract_scene_classes(scene_code)
    scene_code_file_path = f"codes/scene/{class_name}.py"

    write_scene_code_to_file(last_code, class_name)
    write_last_code(last_code)

    err_msg = generate_video(
        uuid_str=uuid_str,
        user_message=user_message,
        quality=quality,
        scene_code_file_path=scene_code_file_path,
        class_name=class_name,
        description=scene_plan,
        err_message="",
        scene_code=last_code,
    )

    error_message = err_msg or read_error_log()
    save_list = None

    if error_message is None:
        second_video_path = f"{target_folder}/video_{uuid_str}.mp4"
        save_list = None

        if quality == "high":
            video_dir = f"media/videos/{class_name}/1080p60/sections"
        elif quality == "medium":
            video_dir = f"media/videos/{class_name}/720p30/sections"
        else:
            video_dir = f"media/videos/{class_name}/480p15/sections"

        print("Initial scene rendering succeeded.")

        base64_list, image_json_list = extract_uniform_frames_as_base64(
            video_dir,
            class_name,
        )
        print(f"Extracted frame count: {len(base64_list)}")

        ssrm.put("Visual representation layer", "base64_list", base64_list)
        save_list = save_images_with_sections(image_json_list, video_dir, last_code)

        copy_frames_to_target_folder(uuid_str, class_name, quality)

        print("Rendering agent is generating geometric constraint correction information.")
        geometric_constraint_correction_module_information = (
            await rendering_agent.get_geometric_constraint_correction_module_information()
        )
        ssrm.put(
            "Semantic layer",
            "geometric_constraint_correction_module_information",
            geometric_constraint_correction_module_information,
        )
        print(
            "Geometric constraint correction information generated by rendering agent: "
            f"{geometric_constraint_correction_module_information}"
        )

        print("Rendering agent is generating corrected scene code and geometric structure.")
        fix_error_code, geometric_structure_extraction_corrected = (
            await rendering_agent.fix_error()
        )

        ssrm.put("Semantic layer", "fix_error_code", fix_error_code)
        ssrm.put(
            "Geometric structure layer",
            "geometric_structure_extraction_corrected",
            geometric_structure_extraction_corrected,
        )

        print(f"Corrected scene code generated by rendering agent: {fix_error_code}")
        print(
            "Corrected geometric structure generated by rendering agent: "
            f"{geometric_structure_extraction_corrected}"
        )

        last_code = fix_error_code
        ssrm.put("Semantic layer", "fix_error_code", last_code)

        class_name = extract_scene_classes(last_code)
        scene_code_file_path = f"codes/scene/{class_name}.py"

        write_scene_code_to_file(last_code, class_name)
        write_last_code(last_code)

        err_msg = generate_video(
            uuid_str=uuid_str,
            user_message=user_message,
            quality=quality,
            scene_code_file_path=scene_code_file_path,
            class_name=class_name,
            description=scene_plan,
            err_message="",
            scene_code=last_code,
        )

        error_message = err_msg or read_error_log()

        if error_message is None:
            target_folder = f"{user_data_folder}/user_data_{uuid_str}"
            first_video_path = f"{target_folder}/video_{uuid_str}.mp4"

            if quality == "high":
                video_dir = f"media/videos/{class_name}/1080p60/sections"
            elif quality == "medium":
                video_dir = f"media/videos/{class_name}/720p30/sections"
            else:
                video_dir = f"media/videos/{class_name}/480p15/sections"

            base64_list, image_json_list = extract_uniform_frames_as_base64(
                video_dir,
                class_name,
            )
            print(f"Extracted frame count: {len(base64_list)}")

            ssrm.put("Visual representation layer", "base64_list", base64_list)
            save_list = save_images_with_sections(image_json_list, video_dir, last_code)

            copy_frames_to_target_folder(uuid_str, class_name, quality)

            try:
                os.remove(scene_code_file_path)
            except Exception:
                pass

        else:
            print("Rendering failed after multimodal correction. Entering retry loop.")
            curr_version = 0
            error_message = None
            last_code = scene_code

            while True:
                error_message = err_msg or read_error_log()
                tex_error_message = error_tool(error_message, raw=True)
                all_error_message = (
                    f"{error_message}\n\nTex Error Fix Suggestion:\n{tex_error_message}"
                )

                ssrm.put("Semantic layer", "error_message", all_error_message)

                print("Error message:", all_error_message)

                if error_message is None:
                    break

                if curr_version >= max_retries:
                    print(f"Maximum retry count reached ({max_retries}). Exiting.")
                    break

                curr_version += 1
                print(f"Starting retry attempt {curr_version}.")

                print("Rendering agent is generating corrected scene code and geometric structure.")
                fix_error_code, geometric_structure_extraction_corrected = (
                    await rendering_agent.fix_error()
                )

                ssrm.put("Semantic layer", "fix_error_code", fix_error_code)
                ssrm.put(
                    "Geometric structure layer",
                    "geometric_structure_extraction_corrected",
                    geometric_structure_extraction_corrected,
                )

                print(f"Corrected scene code generated by rendering agent: {fix_error_code}")
                print(
                    "Corrected geometric structure generated by rendering agent: "
                    f"{geometric_structure_extraction_corrected}"
                )

                if not fix_error_code or not fix_error_code.strip():
                    continue

                last_code = fix_error_code
                ssrm.put("Semantic layer", "fix_error_code", last_code)

                class_name = extract_scene_classes(last_code)
                scene_code_file_path = f"codes/scene/{class_name}.py"

                write_scene_code_to_file(last_code, class_name)
                write_last_code(last_code)

                err_msg = generate_video(
                    uuid_str=uuid_str,
                    user_message=user_message,
                    quality=quality,
                    scene_code_file_path=scene_code_file_path,
                    class_name=class_name,
                    description=scene_plan,
                    err_message="",
                    scene_code=last_code,
                )

                error_message = err_msg or read_error_log()

                if error_message is not None:
                    continue

                target_folder = f"{user_data_folder}/user_data_{uuid_str}"
                first_video_path = f"{target_folder}/video_{uuid_str}.mp4"

                if not os.path.exists(first_video_path):
                    continue

                if quality == "high":
                    video_dir = f"media/videos/{class_name}/1080p60/sections"
                elif quality == "medium":
                    video_dir = f"media/videos/{class_name}/720p30/sections"
                else:
                    video_dir = f"media/videos/{class_name}/480p15/sections"

                base64_list, image_json_list = extract_uniform_frames_as_base64(
                    video_dir,
                    class_name,
                )
                print(f"Extracted frame count: {len(base64_list)}")

                ssrm.put("Visual representation layer", "base64_list", base64_list)

                save_list = save_images_with_sections(
                    image_json_list,
                    video_dir,
                    last_code,
                )

                if save_list is None:
                    continue

                copy_frames_to_target_folder(uuid_str, class_name, quality)

                geometric_constraint_correction_module_information = (
                    await rendering_agent.get_geometric_constraint_correction_module_information()
                )
                ssrm.put(
                    "Semantic layer",
                    "geometric_constraint_correction_module_information",
                    geometric_constraint_correction_module_information,
                )

                print("Rendering agent is generating corrected scene code and geometric structure.")
                fix_error_code, geometric_structure_extraction_corrected = (
                    await rendering_agent.fix_error()
                )

                ssrm.put("Semantic layer", "fix_error_code", fix_error_code)
                ssrm.put(
                    "Geometric structure layer",
                    "geometric_structure_extraction_corrected",
                    geometric_structure_extraction_corrected,
                )

                print(f"Corrected scene code generated by rendering agent: {fix_error_code}")
                print(
                    "Corrected geometric structure generated by rendering agent: "
                    f"{geometric_structure_extraction_corrected}"
                )

                last_code = fix_error_code
                ssrm.put("Semantic layer", "fix_error_code", last_code)

                class_name = extract_scene_classes(last_code)
                scene_code_file_path = f"codes/scene/{class_name}.py"

                write_scene_code_to_file(last_code, class_name)
                write_last_code(last_code)

                err_msg = generate_video(
                    uuid_str=uuid_str,
                    user_message=user_message,
                    quality=quality,
                    scene_code_file_path=scene_code_file_path,
                    class_name=class_name,
                    description=scene_plan,
                    err_message="",
                    scene_code=last_code,
                )

                error_message = err_msg or read_error_log()

                if error_message is not None:
                    continue

                target_folder = f"{user_data_folder}/user_data_{uuid_str}"
                first_video_path = f"{target_folder}/video_{uuid_str}.mp4"

                if not os.path.exists(first_video_path):
                    continue

                if quality == "high":
                    video_dir = f"media/videos/{class_name}/1080p60/sections"
                elif quality == "medium":
                    video_dir = f"media/videos/{class_name}/720p30/sections"
                else:
                    video_dir = f"media/videos/{class_name}/480p15/sections"

                base64_list, image_json_list = extract_uniform_frames_as_base64(
                    video_dir,
                    class_name,
                )
                print(f"Extracted frame count: {len(base64_list)}")

                ssrm.put("Visual representation layer", "base64_list", base64_list)

                save_list = save_images_with_sections(
                    image_json_list,
                    video_dir,
                    last_code,
                )

                if save_list is None:
                    continue

                copy_frames_to_target_folder(uuid_str, class_name, quality)

                try:
                    os.remove(scene_code_file_path)
                except Exception:
                    pass

            print(f"Video generation succeeded after {curr_version} retries.")

    else:
        print("Initial rendering failed. Entering retry loop.")
        curr_version = 0
        error_message = None
        last_code = scene_code

        while True:
            error_message = err_msg or read_error_log()
            tex_error_message = error_tool(error_message, raw=True)
            all_error_message = (
                f"{error_message}\n\nTex Error Fix Suggestion:\n{tex_error_message}"
            )

            ssrm.put("Semantic layer", "error_message", all_error_message)

            print("Error message:", all_error_message)

            if error_message is None:
                break

            if curr_version >= max_retries:
                print(f"Maximum retry count reached ({max_retries}). Exiting.")
                break

            curr_version += 1
            print(f"Starting retry attempt {curr_version}.")

            print("Rendering agent is generating corrected scene code and geometric structure.")
            fix_error_code, geometric_structure_extraction_corrected = (
                await rendering_agent.fix_error()
            )

            ssrm.put("Semantic layer", "fix_error_code", fix_error_code)
            ssrm.put(
                "Geometric structure layer",
                "geometric_structure_extraction_corrected",
                geometric_structure_extraction_corrected,
            )

            print(f"Corrected scene code generated by rendering agent: {fix_error_code}")
            print(
                "Corrected geometric structure generated by rendering agent: "
                f"{geometric_structure_extraction_corrected}"
            )

            if not fix_error_code or not fix_error_code.strip():
                continue

            last_code = fix_error_code
            ssrm.put("Semantic layer", "fix_error_code", last_code)

            class_name = extract_scene_classes(last_code)
            scene_code_file_path = f"codes/scene/{class_name}.py"

            write_scene_code_to_file(last_code, class_name)
            write_last_code(last_code)

            err_msg = generate_video(
                uuid_str=uuid_str,
                user_message=user_message,
                quality=quality,
                scene_code_file_path=scene_code_file_path,
                class_name=class_name,
                description=scene_plan,
                err_message="",
                scene_code=last_code,
            )

            error_message = err_msg or read_error_log()

            if error_message is not None:
                continue

            target_folder = f"{user_data_folder}/user_data_{uuid_str}"
            first_video_path = f"{target_folder}/video_{uuid_str}.mp4"

            if not os.path.exists(first_video_path):
                continue

            if quality == "high":
                video_dir = f"media/videos/{class_name}/1080p60/sections"
            elif quality == "medium":
                video_dir = f"media/videos/{class_name}/720p30/sections"
            else:
                video_dir = f"media/videos/{class_name}/480p15/sections"

            base64_list, image_json_list = extract_uniform_frames_as_base64(
                video_dir,
                class_name,
            )
            print(f"Extracted frame count: {len(base64_list)}")

            ssrm.put("Visual representation layer", "base64_list", base64_list)

            save_list = save_images_with_sections(image_json_list, video_dir, last_code)

            if save_list is None:
                continue

            copy_frames_to_target_folder(uuid_str, class_name, quality)

            geometric_constraint_correction_module_information = (
                await rendering_agent.get_geometric_constraint_correction_module_information()
            )
            ssrm.put(
                "Semantic layer",
                "geometric_constraint_correction_module_information",
                geometric_constraint_correction_module_information,
            )

            fix_error_code, geometric_structure_extraction_corrected = (
                await rendering_agent.fix_error()
            )

            ssrm.put("Semantic layer", "fix_error_code", fix_error_code)
            ssrm.put(
                "Geometric structure layer",
                "geometric_structure_extraction_corrected",
                geometric_structure_extraction_corrected,
            )

            print(f"Corrected scene code generated by rendering agent: {fix_error_code}")
            print(
                "Corrected geometric structure generated by rendering agent: "
                f"{geometric_structure_extraction_corrected}"
            )

            last_code = fix_error_code
            ssrm.put("Semantic layer", "fix_error_code", last_code)

            class_name = extract_scene_classes(last_code)
            scene_code_file_path = f"codes/scene/{class_name}.py"

            write_scene_code_to_file(last_code, class_name)
            write_last_code(last_code)

            err_msg = generate_video(
                uuid_str=uuid_str,
                user_message=user_message,
                quality=quality,
                scene_code_file_path=scene_code_file_path,
                class_name=class_name,
                description=scene_plan,
                err_message="",
                scene_code=last_code,
            )

            error_message = err_msg or read_error_log()

            if error_message is not None:
                continue

            target_folder = f"{user_data_folder}/user_data_{uuid_str}"
            first_video_path = f"{target_folder}/video_{uuid_str}.mp4"

            if not os.path.exists(first_video_path):
                continue

            if quality == "high":
                video_dir = f"media/videos/{class_name}/1080p60/sections"
            elif quality == "medium":
                video_dir = f"media/videos/{class_name}/720p30/sections"
            else:
                video_dir = f"media/videos/{class_name}/480p15/sections"

            base64_list, image_json_list = extract_uniform_frames_as_base64(
                video_dir,
                class_name,
            )
            print(f"Extracted frame count: {len(base64_list)}")

            ssrm.put("Visual representation layer", "base64_list", base64_list)

            save_list = save_images_with_sections(image_json_list, video_dir, last_code)

            if save_list is None:
                continue

            copy_frames_to_target_folder(uuid_str, class_name, quality)

            try:
                os.remove(scene_code_file_path)
            except Exception:
                pass

        print(f"Video generation succeeded after {curr_version} retries.")

    if os.path.exists(cfg.TEMP_JSON_PATH):
        copy_ssrm_to_target_folder(uuid_str)
        copy_user_data_to_generation_data(uuid_str, topic, difficulty)
        ssrm.clear()

        elapsed = time.perf_counter() - start_perf
        finished_at_ms = int(time.time() * 1000)

        return save_generation_metrics_json(
            topic=topic,
            difficulty=difficulty,
            status="success",
            curr_version=curr_version,
            started_at_ms=started_at_ms,
            finished_at_ms=finished_at_ms,
            elapsed_seconds=elapsed,
        )

    elapsed = time.perf_counter() - start_perf
    finished_at_ms = int(time.time() * 1000)

    return save_generation_metrics_json(
        topic=topic,
        difficulty=difficulty,
        status="failed",
        curr_version=curr_version,
        started_at_ms=started_at_ms,
        finished_at_ms=finished_at_ms,
        elapsed_seconds=elapsed,
    )